### ISSUE TITLE
getsections.php

### ISSUE THREAD

**Issue by ghost** [MrGoatsy/GoatBB#1]
Parse error: syntax error, unexpected '?' in /home/u562210452/public_html/en/functions/getsections.php on line 13

https://sipws.com/en/

**Comment by MrGoatsy** [comment]
Do you have PHP 7 installed?

**Comment by ghost** [comment]
yes

**Comment by MrGoatsy** [comment]
Then I don't know, the project is no longer active.

Sorry.
